image_width: 736
image_height: 736
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [373.09077,   0.70452, 367.16391,
           0.     , 377.28895, 367.55198,
           0.     ,   0.     ,   1.     ]
distortion_model: equidistant
distortion_coefficients:
  rows: 1
  cols: 4
  data: [0.103583, -2.752804, 6.513619, -1.478954]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [373.09077,   0.70452, 367.16391,   0.     ,
           0.     , 377.28895, 367.55198,   0.     ,
           0.     ,   0.     ,   1.     ,   0.     ]
